// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: weather.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	mi := &file_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type WeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float32                `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Conditions    string                 `protobuf:"bytes,2,opt,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherResponse) Reset() {
	*x = WeatherResponse{}
	mi := &file_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherResponse) ProtoMessage() {}

func (x *WeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherResponse.ProtoReflect.Descriptor instead.
func (*WeatherResponse) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherResponse) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherResponse) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

// New Message for writing data
type UpdateWeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Temperature   float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Conditions    string                 `protobuf:"bytes,3,opt,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWeatherRequest) Reset() {
	*x = UpdateWeatherRequest{}
	mi := &file_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWeatherRequest) ProtoMessage() {}

func (x *UpdateWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWeatherRequest.ProtoReflect.Descriptor instead.
func (*UpdateWeatherRequest) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWeatherRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateWeatherRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *UpdateWeatherRequest) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

// Simple response to acknowledge success
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_weather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_weather_proto protoreflect.FileDescriptor

const file_weather_proto_rawDesc = "" +
	"\n" +
	"\rweather.proto\x12\aweather\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\x0eWeatherRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"S\n" +
	"\x0fWeatherResponse\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12\x1e\n" +
	"\n" +
	"conditions\x18\x02 \x01(\tR\n" +
	"conditions\"l\n" +
	"\x14UpdateWeatherRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12\x1e\n" +
	"\n" +
	"conditions\x18\x03 \x01(\tR\n" +
	"conditions\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8a\x02\n" +
	"\x0eWeatherService\x12b\n" +
	"\x11GetCurrentWeather\x12\x17.weather.WeatherRequest\x1a\x18.weather.WeatherResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/weather/{city}\x12K\n" +
	"\x14StreamWeatherUpdates\x12\x17.weather.WeatherRequest\x1a\x18.weather.WeatherResponse0\x01\x12G\n" +
	"\rUpdateWeather\x12\x1d.weather.UpdateWeatherRequest\x1a\x17.weather.UpdateResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_weather_proto_rawDescOnce sync.Once
	file_weather_proto_rawDescData []byte
)

func file_weather_proto_rawDescGZIP() []byte {
	file_weather_proto_rawDescOnce.Do(func() {
		file_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)))
	})
	return file_weather_proto_rawDescData
}

var file_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_weather_proto_goTypes = []any{
	(*WeatherRequest)(nil),       // 0: weather.WeatherRequest
	(*WeatherResponse)(nil),      // 1: weather.WeatherResponse
	(*UpdateWeatherRequest)(nil), // 2: weather.UpdateWeatherRequest
	(*UpdateResponse)(nil),       // 3: weather.UpdateResponse
}
var file_weather_proto_depIdxs = []int32{
	0, // 0: weather.WeatherService.GetCurrentWeather:input_type -> weather.WeatherRequest
	0, // 1: weather.WeatherService.StreamWeatherUpdates:input_type -> weather.WeatherRequest
	2, // 2: weather.WeatherService.UpdateWeather:input_type -> weather.UpdateWeatherRequest
	1, // 3: weather.WeatherService.GetCurrentWeather:output_type -> weather.WeatherResponse
	1, // 4: weather.WeatherService.StreamWeatherUpdates:output_type -> weather.WeatherResponse
	3, // 5: weather.WeatherService.UpdateWeather:output_type -> weather.UpdateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weather_proto_init() }
func file_weather_proto_init() {
	if File_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weather_proto_goTypes,
		DependencyIndexes: file_weather_proto_depIdxs,
		MessageInfos:      file_weather_proto_msgTypes,
	}.Build()
	File_weather_proto = out.File
	file_weather_proto_goTypes = nil
	file_weather_proto_depIdxs = nil
}
